### ISSUE TITLE
magnetization dynamics failed with CUDA (I have no idea what I am doing)

### ISSUE THREAD

**Issue by bertdupe** [bertdupe/Matjes#68]
Hello,

there might be a problem with CUDA and the magnetization dynamics (no problem at compilation). When running on my PC, I get
Matjes: /home/bdupe/Matjes/src/Hamiltonian_type/cuda_H.cu:42: void cuda_create_handle(cusparseContext**&): Assertion `CUSPARSE_STATUS_SUCCESS == stat' failed.

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x7fe5e637ad21 in ???
#1  0x7fe5e6379ef5 in ???
#2  0x7fe5e614920f in ???
#3  0x7fe5e614918b in ???
#4  0x7fe5e6128858 in ???
#5  0x7fe5e6128728 in ???
#6  0x7fe5e6139f35 in ???
#7  0x55a6ff217eb9 in cuda_create_handle
	at /home/bdupe/Matjes/src/Hamiltonian_type/cuda_H.cu:42
#8  0x55a6fee93ab3 in __m_h_cusparse_MOD_set_from_hcoo
	at /home/bdupe/Matjes/src/Hamiltonian_type/ham_cusparse.f90:147
#9  0x55a6fee9004d in __m_h_coo_based_MOD_init_connect
	at /home/bdupe/Matjes/src/Hamiltonian_type/ham_coo_based.f90:62
#10  0x55a6fede04a6 in __m_exchange_heisenberg_j_MOD_get_exchange_j
	at /home/bdupe/Matjes/src/Energy/exchange_Heisenberg_J.f90:111
#11  0x55a6fedf4691 in __m_set_hamiltonians_MOD_set_hamiltonians
	at /home/bdupe/Matjes/src/Energy/set_Hamiltonians.f90:57
#12  0x55a6ff022301 in __m_setup_simu_MOD_setup_simu
	at /home/bdupe/Matjes/src/setup/setup-simu.f90:115
#13  0x55a6fedae7bf in matjes
	at /home/bdupe/Matjes/src/main.f90:65
#14  0x55a6fedaed58 in main
	at /home/bdupe/Matjes/src/main.f90:5

**Comment by bertdupe** [comment]
the problem is solved.
I do not know what happened but it works fine

**Comment by bertdupe** [comment]
so far so good
