### ISSUE TITLE
mpi comms get stuck after the butchers table

### ISSUE THREAD

**Issue by bertdupe** [bertdupe/Matjes#70]
upon execution, I get the message

At line 341 of file /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90
Fortran runtime error: Index '1' of dimension 1 of array 'e' above upper bound of 0

Error termination. Backtrace:
#0  0x7f18bc238d21 in ???
#1  0x7f18bc239869 in ???
#2  0x7f18bc239ee6 in ???
#0  0x7f9da7ab5d21 in ???
#1  0x7f9da7ab6869 in ???
#2  0x7f9da7ab6ee6 in ???
#0  0x7f7a15079d21 in ???
#1  0x7f7a1507a869 in ???
#2  0x7f7a1507aee6 in ???
#3  0x564ae88e81cd in __m_hamiltonian_collection_MOD_energy_resolved
	at /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90:341
#4  0x564ae88e7dba in __m_hamiltonian_collection_MOD_energy
	at /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90:359
#3  0x55aa909a81cd in __m_hamiltonian_collection_MOD_energy_resolved
	at /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90:341
#4  0x55aa909a7dba in __m_hamiltonian_collection_MOD_energy
	at /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90:359
#3  0x55dc27a391cd in __m_hamiltonian_collection_MOD_energy_resolved
	at /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90:341
#4  0x55dc27a38dba in __m_hamiltonian_collection_MOD_energy
	at /home/bdupe/Matjes/src/Hamiltonian_type/hamiltonian_collection.f90:359
#5  0x564ae87f1424 in __m_spindynamics_MOD_spindynamics_run
	at /home/bdupe/Matjes/src/dynamics/spindynamics.f90:182
#6  0x564ae87f41eb in __m_spindynamics_MOD_spindynamics
	at /home/bdupe/Matjes/src/dynamics/spindynamics.f90:30
#5  0x55dc27942424 in __m_spindynamics_MOD_spindynamics_run
	at /home/bdupe/Matjes/src/dynamics/spindynamics.f90:182
#6  0x55dc279451eb in __m_spindynamics_MOD_spindynamics
	at /home/bdupe/Matjes/src/dynamics/spindynamics.f90:30
#7  0x55dc2792f467 in matjes
	at /home/bdupe/Matjes/src/main.f90:96
#8  0x55dc2792f7d9 in main
	at /home/bdupe/Matjes/src/main.f90:5
#5  0x55aa908b1424 in __m_spindynamics_MOD_spindynamics_run
	at /home/bdupe/Matjes/src/dynamics/spindynamics.f90:182
#6  0x55aa908b41eb in __m_spindynamics_MOD_spindynamics
	at /home/bdupe/Matjes/src/dynamics/spindynamics.f90:30
#7  0x55aa9089e467 in matjes
	at /home/bdupe/Matjes/src/main.f90:96
#8  0x55aa9089e7d9 in main
	at /home/bdupe/Matjes/src/main.f90:5
#7  0x564ae87de467 in matjes
	at /home/bdupe/Matjes/src/main.f90:96
#8  0x564ae87de7d9 in main
	at /home/bdupe/Matjes/src/main.f90:5
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[63541,1],3]
  Exit code:    2

**Comment by patrick432** [comment]
I guess N_total get initialized incorrectly in the mpi-distribution of the Hamiltonian.

But without input that is difficult to check.

**Comment by bertdupe** [comment]
this is still on. It seems that the mpicom outer and inner and doing strange stuff.
Patrick, you have coded 2 types of parallelization. Where are they initialized?
